package com.example.bilingualb8.repositories.custom.impl;

import com.example.bilingualb8.repositories.custom.CustomRecordSayingStatementQuestionRepository;

public class CustomRecordSayingStatementQuestionRepositoryImpl implements CustomRecordSayingStatementQuestionRepository {
}
